servers:
  - id: 5b-00               # CLI で参照する server_id
    # host: 192.168.40.45
    host: 5b-00.local
    port: 8765
    endpoint: /ws
    default_require_result: true  # 省略時は false
    cubes:
      - id: Q7B
  - id: 5b-01
    host: 5b-01.local
    port: 8765
    endpoint: /ws
    default_require_result: true  # 省略時は false
    cubes:
      - id: 38t
  - id: 5b-02
    host: 5b-02.local
    port: 8765
    endpoint: /ws
    default_require_result: true  # 省略時は false
    cubes:
      - id: p2K
